#!/bin/sh
# Xsetup - run as root before the login dialog appears

# Multi monitor setup on login screen
# -----------------------------------
# source: blog.victormendonca.com/2018/06/29/how-to-fix-sddm-on-multiple-screens/
# command: xrandr | grep ' connected'
xrandr --output DP-8 --auto --primary
# xrandr --output HDMI-1 --right-of DP-8 --rotate right --noprimary
# xrandr --output HDMI-2 --left-of DP-8 --rotate left --noprimary

xrandr --output HDMI-1 --off
xrandr --output HDMI-2 --off
